"""audit columns created_by and updated_at

Revision ID: 093cf2d8eda3
Revises: 142ba692737d
Create Date: 2026-07-02 22:37:25.535779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093cf2d8eda3'
down_revision: Union[str, None] = '142ba692737d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('budgets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'budgets', 'users', ['created_by'], ['id'])
    op.add_column('clients', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'clients', 'users', ['created_by'], ['id'])
    op.add_column('engineering', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('engineering', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('engineering', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'engineering', 'users', ['created_by'], ['id'])
    op.add_column('extensions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('extensions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'extensions', 'users', ['created_by'], ['id'])
    op.add_column('invoices', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'users', ['created_by'], ['id'])
    op.add_column('log_entries', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('materials', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('materials', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'materials', 'users', ['created_by'], ['id'])
    op.add_column('pre_invoices', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('pre_invoices', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'pre_invoices', 'users', ['created_by'], ['id'])
    op.add_column('products', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'])
    op.add_column('projects', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])
    op.add_column('quotes', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('quotes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'quotes', 'users', ['created_by'], ['id'])
    op.add_column('surveys', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('surveys', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('surveys', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'surveys', 'users', ['created_by'], ['id'])
    op.add_column('tickets', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'updated_at')
    op.drop_column('tickets', 'created_by')
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_column('surveys', 'updated_at')
    op.drop_column('surveys', 'created_at')
    op.drop_column('surveys', 'created_by')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_column('quotes', 'updated_at')
    op.drop_column('quotes', 'created_by')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'created_by')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'created_by')
    op.drop_constraint(None, 'pre_invoices', type_='foreignkey')
    op.drop_column('pre_invoices', 'updated_at')
    op.drop_column('pre_invoices', 'created_by')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_column('materials', 'updated_at')
    op.drop_column('materials', 'created_by')
    op.drop_column('log_entries', 'updated_at')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'created_by')
    op.drop_constraint(None, 'extensions', type_='foreignkey')
    op.drop_column('extensions', 'updated_at')
    op.drop_column('extensions', 'created_by')
    op.drop_constraint(None, 'engineering', type_='foreignkey')
    op.drop_column('engineering', 'updated_at')
    op.drop_column('engineering', 'created_at')
    op.drop_column('engineering', 'created_by')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'created_at')
    op.drop_column('clients', 'created_by')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_column('budgets', 'updated_at')
    op.drop_column('budgets', 'created_by')
    # ### end Alembic commands ###
